package com.bluezone.bil.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bluezone.bil.domain.cust.CstCustRecordMst;
import com.bluezone.bil.domain.cust.CstCustRecordMstExample;

public interface CstCustRecordMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int countByExample(CstCustRecordMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int deleteByExample(CstCustRecordMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int deleteByPrimaryKey(Integer custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int insert(CstCustRecordMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int insertSelective(CstCustRecordMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    List<CstCustRecordMst> selectByExample(CstCustRecordMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    CstCustRecordMst selectByPrimaryKey(Integer custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int updateByExampleSelective(@Param("record") CstCustRecordMst record, @Param("example") CstCustRecordMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int updateByExample(@Param("record") CstCustRecordMst record, @Param("example") CstCustRecordMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int updateByPrimaryKeySelective(CstCustRecordMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    int updateByPrimaryKey(CstCustRecordMst record);
}