package com.bluezone.bil.dao.game.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bluezone.bil.domain.game.GameCustComp;
import com.bluezone.bil.domain.game.GameRecord;
import com.bluezone.bil.domain.game.GameRecordExample;

public interface GameRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int countByExample(GameRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int deleteByExample(GameRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int deleteByPrimaryKey(Integer gameRecNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int insert(GameRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int insertSelective(GameRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    List<GameRecord> selectByExample(GameRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    GameRecord selectByPrimaryKey(Integer gameRecNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int updateByExampleSelective(@Param("record") GameRecord record, @Param("example") GameRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int updateByExample(@Param("record") GameRecord record, @Param("example") GameRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int updateByPrimaryKeySelective(GameRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    int updateByPrimaryKey(GameRecord record);

	List<GameCustComp> selectGameWithCustInfo(Integer gameNo);
	
	List<GameCustComp> selectTotalCustGameRecordList(Integer custNo);
}