package com.bluezone.bil.dao.game.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bluezone.bil.domain.game.GameRecordInning;
import com.bluezone.bil.domain.game.GameRecordInningExample;

public interface GameRecordInningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int countByExample(GameRecordInningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int deleteByExample(GameRecordInningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int insert(GameRecordInning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int insertSelective(GameRecordInning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    List<GameRecordInning> selectByExample(GameRecordInningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int updateByExampleSelective(@Param("record") GameRecordInning record, @Param("example") GameRecordInningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    int updateByExample(@Param("record") GameRecordInning record, @Param("example") GameRecordInningExample example);
}