## 회원정보
#------------------------
-- DROP TABLE CST_CUST_MST;
CREATE TABLE CST_CUST_MST(
	CUST_NO INT(10) NOT NULL AUTO_INCREMENT AUTO_INCREMENT PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	USE_YN VARCHAR(1) NOT NULL COMMENT '사용여부',
	CUST_NM VARCHAR(30) NOT NULL COMMENT '고객명',
	EMAIL VARCHAR(100) NOT NULL COMMENT '이메일',
	PASSWD VARCHAR(100) NOT NULL COMMENT '비밀번호',
	NICK_NAME VARCHAR(50) NOT NULL COMMENT '닉네임',
	WITHDRAW_DATE VARCHAR(8)  COMMENT '탈퇴일자'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;


## 회원기록기본
#------------------------
-- DROP TABLE CST_CUST_RECORD_MST;
CREATE TABLE CST_CUST_RECORD_MST(
	CUST_NO INT(10) NOT NULL PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	SCORE INT(3) NOT NULL COMMENT '수지',
	SCORE_AVG FLOAT(10) COMMENT '수지평균',
	AVG FLOAT(10) COMMENT '에버리지',
	HIGH_RUN INT(2) COMMENT '하이런',
	WIN_CNT INT(5) COMMENT '승리경기수',
	LOSE_CNT INT(5)  COMMENT '패전경기수',
	DRAW_CNT INT(5)  COMMENT '무승부경기수',
	INDEX IX_CST_CUST_RECORD_MST_01 (CUST_NO)
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;

## 대회기본
#------------------------
-- DROP TABLE MATCH_MST;
CREATE TABLE MATCH_MST(
	MATCH_NO INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	MATCH_NM VARCHAR(100) NOT NULL COMMENT '대회명',
	USE_YN VARCHAR(1) NOT NULL COMMENT '사용여부',
	MATCH_DT VARCHAR(8) COMMENT '대회일자',
	YYYYMM VARCHAR(6) COMMENT '년월',
	WEEK VARCHAR(1) COMMENT '주',
	MATCH_TYPE VARCHAR(2) COMMENT '대회유형'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;

## 게임기본
#------------------------
-- DROP TABLE GAME_MST;
CREATE TABLE GAME_MST(
	GAME_NO INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	MATCH_NO INT(10) NOT NULL COMMENT '대회번호',
	GAME_NM VARCHAR(100) COMMENT '게임명',
	USE_YN VARCHAR(1) NOT NULL COMMENT '사용여부',
	GAME_DT VARCHAR(8) COMMENT '게임일자',
	MEM_CNT INT(2) NOT NULL COMMENT '참여인원',
	INNING_CNT INT(3) COMMENT '이닝수',
	FOREIGN KEY (MATCH_NO) 
        REFERENCES MATCH_MST(MATCH_NO)
        ON DELETE CASCADE

)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;

CREATE INDEX IX_GAME_MST_01 ON GAME_MST ( MATCH_NO );

## 게임기록
#------------------------
-- DROP TABLE GAME_RECORD;
CREATE TABLE GAME_RECORD(
	GAME_REC_NO INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	GAME_NO INT(10) NOT NULL COMMENT '게임번호',
	CUST_NO INT(10) NOT NULL COMMENT '고객번호',
	SCORE INT(3) NOT NULL COMMENT '수지',
	INNING INT(3) COMMENT '이닝',
	EARN_SCORE INT(3) COMMENT '득점',
	AVG FLOAT(10) COMMENT '에버리지',
	HIGH_RUN INT(2) COMMENT '하이런',
	WIN_CNT INT(1) COMMENT '승',
	LOSE_CNT INT(1) COMMENT '패',
	DRAW_CNT INT(1) COMMENT '무'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;

CREATE INDEX IX_GAME_RECORD_01 ON GAME_RECORD ( GAME_NO );


## 게임이닝기록
#------------------------
-- DROP TABLE GAME_RECORD_INNING;
CREATE TABLE GAME_RECORD_INNING(
	GAME_REC_NO INT(10) NOT NULL COMMENT '게임상세번호',
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	INNING_NUM INT(3) NOT NULL COMMENT '이닝번호',
	EARN_SCORE INT(3) NOT NULL COMMENT '득점'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;

CREATE UNIQUE INDEX IX_GAME_RECORD_INNING_01 ON GAME_RECORD_INNING ( GAME_REC_NO );


## [Sample Data]
insert into match_mst (Reg_DTM, REGR_ID, UPD_DTM, UPDR_ID, MATCH_NM, MATCH_DT, YYYYMM, WEEK, MATCH_TYPE,use_yn)
values(sysdate(),'system',sysdate(),'system','15회정기대회','20130930','201309','5', '1','Y');

insert into game_mst (Reg_DTM, REGR_ID, UPD_DTM, UPDR_ID, MATCH_no, game_nm, use_yn, game_dt, mem_cnt, inning_cnt)
values(sysdate(),'system',sysdate(),'system', 1, 'test game', 'Y', '20130929', 2, 40);

select MATCH_NO, REG_DTM, REGR_ID, UPD_DTM, UPDR_ID, MATCH_NM, USE_YN, MATCH_DT, YYYYMM, WEEK, MATCH_TYPE 
from match_mst 
WHERE ( MATCH_DT >= '20130929' ) ;

select GAME_NO, REG_DTM, REGR_ID, UPD_DTM, UPDR_ID, MATCH_NO, GAME_NM, USE_YN, GAME_DT, MEM_CNT, INNING_CNT 
from game_mst 
WHERE ( MATCH_NO = 1 and USE_YN = 'Y' ) ;


-- GameRecordMapper.selectGameWithCustInfo
SELECT A.*,
        B.CUST_NM,
        B.EMAIL,
        B.NICK_NAME,
        C.SCORE AS CUST_SCORE,
        C.SCORE_AVG AS CUST_SCORE_AVG,
        C.AVG AS CUST_AVG,
        C.HIGH_RUN AS CUST_HIGH_RUN,
        C.WIN_CNT AS CUST_WIN_CNT,
        C.LOSE_CNT AS CUST_LOSE_CNT,
        C.DRAW_CNT AS CUST_DRAW_CNT
FROM  GAME_RECORD A,
	   CST_CUST_MST B
LEFT JOIN CST_CUST_RECORD_MST C ON B.CUST_NO=C.CUST_NO 
WHERE A.GAME_NO = 1
  AND A.CUST_NO = B.CUST_NO
  AND B.USE_YN = 'Y';