## 회원정보
#------------------------
-- DROP TABLE CST_CUST_MST;
CREATE TABLE CST_CUST_MST(
	CUST_NO INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	USE_YN VARCHAR(1) NOT NULL COMMENT '사용여부',
	CUST_NM VARCHAR(30) NOT NULL COMMENT '고객명',
	EMAIL VARCHAR(100) NOT NULL COMMENT '이메일',
	PASSWD VARCHAR(100) NOT NULL COMMENT '비밀번호',
	NICK_NAME VARCHAR(50) NOT NULL COMMENT '닉네임',
	WITHDRAW_DATE VARCHAR(8)  COMMENT '탈퇴일자'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;


## 회원기록기본
#------------------------
-- DROP TABLE CST_CUST_RECORD_MST;
CREATE TABLE CST_CUST_RECORD_MST(
	CUST_NO INT(10) NOT NULL PRIMARY KEY,
	REG_DTM DATETIME NOT NULL COMMENT '등록일시',
	REGR_ID VARCHAR(30) NOT NULL COMMENT '등록자',
	UPD_DTM DATETIME NOT NULL COMMENT '수정일시',
	UPDR_ID VARCHAR(30) NOT NULL COMMENT '수정자',
	SCORE INT(3) NOT NULL COMMENT '수지',
	SCORE_AVG FLOAT(10) COMMENT '수지평균',
	AVG FLOAT(10) COMMENT '에버리지',
	HIGH_RUN INT(2) COMMENT '하이런',
	WIN_CNT INT(5) COMMENT '승리경기수',
	LOSE_CNT INT(5)  COMMENT '패전경기수',
	DRAW_CNT INT(5)  COMMENT '무승부경기수'
)  DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;