package com.bluezone.bil.dao.cust.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bluezone.bil.domain.cust.CstCustMst;
import com.bluezone.bil.domain.cust.CstCustMstExample;

public interface CstCustMstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int countByExample(CstCustMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int deleteByExample(CstCustMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int deleteByPrimaryKey(Integer custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int insert(CstCustMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int insertSelective(CstCustMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    List<CstCustMst> selectByExample(CstCustMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    CstCustMst selectByPrimaryKey(Integer custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int updateByExampleSelective(@Param("record") CstCustMst record, @Param("example") CstCustMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int updateByExample(@Param("record") CstCustMst record, @Param("example") CstCustMstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int updateByPrimaryKeySelective(CstCustMst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    int updateByPrimaryKey(CstCustMst record);

	CstCustMst dupChkNickName(CstCustMst cstCustMst);

	CstCustMst dupChkEmail(CstCustMst cstCustMst);
}