package com.bluezone.bil.domain.cust;

import java.sql.Timestamp;
import java.util.Date;

public class CstCustMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private Integer custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private Timestamp regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private Timestamp updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.USE_YN
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.CUST_NM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String custNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.EMAIL
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.PASSWD
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.NICK_NAME
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_mst.WITHDRAW_DATE
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    private String withdrawDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.CUST_NO
     *
     * @return the value of cst_cust_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public Integer getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.CUST_NO
     *
     * @param custNo the value for cst_cust_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setCustNo(Integer custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.REG_DTM
     *
     * @return the value of cst_cust_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.REG_DTM
     *
     * @param regDtm the value for cst_cust_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setRegDtm(Timestamp regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.REGR_ID
     *
     * @return the value of cst_cust_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.REGR_ID
     *
     * @param regrId the value for cst_cust_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.UPD_DTM
     *
     * @return the value of cst_cust_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.UPD_DTM
     *
     * @param updDtm the value for cst_cust_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setUpdDtm(Timestamp updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.UPDR_ID
     *
     * @return the value of cst_cust_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.UPDR_ID
     *
     * @param updrId the value for cst_cust_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.USE_YN
     *
     * @return the value of cst_cust_mst.USE_YN
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.USE_YN
     *
     * @param useYn the value for cst_cust_mst.USE_YN
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.CUST_NM
     *
     * @return the value of cst_cust_mst.CUST_NM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getCustNm() {
        return custNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.CUST_NM
     *
     * @param custNm the value for cst_cust_mst.CUST_NM
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setCustNm(String custNm) {
        this.custNm = custNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.EMAIL
     *
     * @return the value of cst_cust_mst.EMAIL
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.EMAIL
     *
     * @param email the value for cst_cust_mst.EMAIL
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.PASSWD
     *
     * @return the value of cst_cust_mst.PASSWD
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.PASSWD
     *
     * @param passwd the value for cst_cust_mst.PASSWD
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.NICK_NAME
     *
     * @return the value of cst_cust_mst.NICK_NAME
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.NICK_NAME
     *
     * @param nickName the value for cst_cust_mst.NICK_NAME
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_mst.WITHDRAW_DATE
     *
     * @return the value of cst_cust_mst.WITHDRAW_DATE
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public String getWithdrawDate() {
        return withdrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_mst.WITHDRAW_DATE
     *
     * @param withdrawDate the value for cst_cust_mst.WITHDRAW_DATE
     *
     * @mbggenerated Sun Sep 22 14:33:34 KST 2013
     */
    public void setWithdrawDate(String withdrawDate) {
        this.withdrawDate = withdrawDate;
    }
}