package com.bluezone.bil.domain.cust;

import java.sql.Timestamp;
import java.util.Date;

public class CstCustRecordMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Timestamp regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Timestamp updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.SCORE
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.SCORE_AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Float scoreAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Float avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.HIGH_RUN
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer highRun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.WIN_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer winCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.LOSE_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer loseCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_cust_record_mst.DRAW_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    private Integer drawCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.CUST_NO
     *
     * @return the value of cst_cust_record_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.CUST_NO
     *
     * @param custNo the value for cst_cust_record_mst.CUST_NO
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setCustNo(Integer custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.REG_DTM
     *
     * @return the value of cst_cust_record_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.REG_DTM
     *
     * @param regDtm the value for cst_cust_record_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setRegDtm(Timestamp regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.REGR_ID
     *
     * @return the value of cst_cust_record_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.REGR_ID
     *
     * @param regrId the value for cst_cust_record_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.UPD_DTM
     *
     * @return the value of cst_cust_record_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.UPD_DTM
     *
     * @param updDtm the value for cst_cust_record_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setUpdDtm(Timestamp updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.UPDR_ID
     *
     * @return the value of cst_cust_record_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.UPDR_ID
     *
     * @param updrId the value for cst_cust_record_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.SCORE
     *
     * @return the value of cst_cust_record_mst.SCORE
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.SCORE
     *
     * @param score the value for cst_cust_record_mst.SCORE
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.SCORE_AVG
     *
     * @return the value of cst_cust_record_mst.SCORE_AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Float getScoreAvg() {
        return scoreAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.SCORE_AVG
     *
     * @param scoreAvg the value for cst_cust_record_mst.SCORE_AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setScoreAvg(Float scoreAvg) {
        this.scoreAvg = scoreAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.AVG
     *
     * @return the value of cst_cust_record_mst.AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Float getAvg() {
        return avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.AVG
     *
     * @param avg the value for cst_cust_record_mst.AVG
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setAvg(Float avg) {
        this.avg = avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.HIGH_RUN
     *
     * @return the value of cst_cust_record_mst.HIGH_RUN
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getHighRun() {
        return highRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.HIGH_RUN
     *
     * @param highRun the value for cst_cust_record_mst.HIGH_RUN
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setHighRun(Integer highRun) {
        this.highRun = highRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.WIN_CNT
     *
     * @return the value of cst_cust_record_mst.WIN_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getWinCnt() {
        return winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.WIN_CNT
     *
     * @param winCnt the value for cst_cust_record_mst.WIN_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setWinCnt(Integer winCnt) {
        this.winCnt = winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.LOSE_CNT
     *
     * @return the value of cst_cust_record_mst.LOSE_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getLoseCnt() {
        return loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.LOSE_CNT
     *
     * @param loseCnt the value for cst_cust_record_mst.LOSE_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setLoseCnt(Integer loseCnt) {
        this.loseCnt = loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_cust_record_mst.DRAW_CNT
     *
     * @return the value of cst_cust_record_mst.DRAW_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Integer getDrawCnt() {
        return drawCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_cust_record_mst.DRAW_CNT
     *
     * @param drawCnt the value for cst_cust_record_mst.DRAW_CNT
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setDrawCnt(Integer drawCnt) {
        this.drawCnt = drawCnt;
    }
}