package com.bluezone.bil.domain.cust;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CstCustMstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public CstCustMstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustNoIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoEqualTo(Integer value) {
            addCriterion("CUST_NO =", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotEqualTo(Integer value) {
            addCriterion("CUST_NO <>", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThan(Integer value) {
            addCriterion("CUST_NO >", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUST_NO >=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThan(Integer value) {
            addCriterion("CUST_NO <", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThanOrEqualTo(Integer value) {
            addCriterion("CUST_NO <=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoIn(List<Integer> values) {
            addCriterion("CUST_NO in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotIn(List<Integer> values) {
            addCriterion("CUST_NO not in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoBetween(Integer value1, Integer value2) {
            addCriterion("CUST_NO between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotBetween(Integer value1, Integer value2) {
            addCriterion("CUST_NO not between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNull() {
            addCriterion("REGR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNotNull() {
            addCriterion("REGR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegrIdEqualTo(String value) {
            addCriterion("REGR_ID =", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotEqualTo(String value) {
            addCriterion("REGR_ID <>", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThan(String value) {
            addCriterion("REGR_ID >", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGR_ID >=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThan(String value) {
            addCriterion("REGR_ID <", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThanOrEqualTo(String value) {
            addCriterion("REGR_ID <=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLike(String value) {
            addCriterion("REGR_ID like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotLike(String value) {
            addCriterion("REGR_ID not like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdIn(List<String> values) {
            addCriterion("REGR_ID in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotIn(List<String> values) {
            addCriterion("REGR_ID not in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdBetween(String value1, String value2) {
            addCriterion("REGR_ID between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotBetween(String value1, String value2) {
            addCriterion("REGR_ID not between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNull() {
            addCriterion("UPD_DTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNotNull() {
            addCriterion("UPD_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmEqualTo(Date value) {
            addCriterion("UPD_DTM =", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotEqualTo(Date value) {
            addCriterion("UPD_DTM <>", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThan(Date value) {
            addCriterion("UPD_DTM >", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM >=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThan(Date value) {
            addCriterion("UPD_DTM <", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM <=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIn(List<Date> values) {
            addCriterion("UPD_DTM in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotIn(List<Date> values) {
            addCriterion("UPD_DTM not in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM not between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNull() {
            addCriterion("UPDR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNotNull() {
            addCriterion("UPDR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdEqualTo(String value) {
            addCriterion("UPDR_ID =", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotEqualTo(String value) {
            addCriterion("UPDR_ID <>", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThan(String value) {
            addCriterion("UPDR_ID >", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDR_ID >=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThan(String value) {
            addCriterion("UPDR_ID <", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThanOrEqualTo(String value) {
            addCriterion("UPDR_ID <=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLike(String value) {
            addCriterion("UPDR_ID like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotLike(String value) {
            addCriterion("UPDR_ID not like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIn(List<String> values) {
            addCriterion("UPDR_ID in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotIn(List<String> values) {
            addCriterion("UPDR_ID not in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdBetween(String value1, String value2) {
            addCriterion("UPDR_ID between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotBetween(String value1, String value2) {
            addCriterion("UPDR_ID not between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUseYnIsNull() {
            addCriterion("USE_YN is null");
            return (Criteria) this;
        }

        public Criteria andUseYnIsNotNull() {
            addCriterion("USE_YN is not null");
            return (Criteria) this;
        }

        public Criteria andUseYnEqualTo(String value) {
            addCriterion("USE_YN =", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotEqualTo(String value) {
            addCriterion("USE_YN <>", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnGreaterThan(String value) {
            addCriterion("USE_YN >", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnGreaterThanOrEqualTo(String value) {
            addCriterion("USE_YN >=", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLessThan(String value) {
            addCriterion("USE_YN <", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLessThanOrEqualTo(String value) {
            addCriterion("USE_YN <=", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLike(String value) {
            addCriterion("USE_YN like", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotLike(String value) {
            addCriterion("USE_YN not like", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnIn(List<String> values) {
            addCriterion("USE_YN in", values, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotIn(List<String> values) {
            addCriterion("USE_YN not in", values, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnBetween(String value1, String value2) {
            addCriterion("USE_YN between", value1, value2, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotBetween(String value1, String value2) {
            addCriterion("USE_YN not between", value1, value2, "useYn");
            return (Criteria) this;
        }

        public Criteria andCustNmIsNull() {
            addCriterion("CUST_NM is null");
            return (Criteria) this;
        }

        public Criteria andCustNmIsNotNull() {
            addCriterion("CUST_NM is not null");
            return (Criteria) this;
        }

        public Criteria andCustNmEqualTo(String value) {
            addCriterion("CUST_NM =", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotEqualTo(String value) {
            addCriterion("CUST_NM <>", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmGreaterThan(String value) {
            addCriterion("CUST_NM >", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NM >=", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLessThan(String value) {
            addCriterion("CUST_NM <", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLessThanOrEqualTo(String value) {
            addCriterion("CUST_NM <=", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLike(String value) {
            addCriterion("CUST_NM like", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotLike(String value) {
            addCriterion("CUST_NM not like", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmIn(List<String> values) {
            addCriterion("CUST_NM in", values, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotIn(List<String> values) {
            addCriterion("CUST_NM not in", values, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmBetween(String value1, String value2) {
            addCriterion("CUST_NM between", value1, value2, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotBetween(String value1, String value2) {
            addCriterion("CUST_NM not between", value1, value2, "custNm");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("PASSWD =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("PASSWD <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("PASSWD >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("PASSWD <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("PASSWD <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("PASSWD like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("PASSWD not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("PASSWD in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("PASSWD not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("PASSWD between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("PASSWD not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("NICK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("NICK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("NICK_NAME =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("NICK_NAME <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("NICK_NAME >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("NICK_NAME >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("NICK_NAME <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("NICK_NAME <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("NICK_NAME like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("NICK_NAME not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("NICK_NAME in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("NICK_NAME not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("NICK_NAME between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("NICK_NAME not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andCustLevelIsNull() {
            addCriterion("CUST_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andCustLevelIsNotNull() {
            addCriterion("CUST_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andCustLevelEqualTo(Integer value) {
            addCriterion("CUST_LEVEL =", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelNotEqualTo(Integer value) {
            addCriterion("CUST_LEVEL <>", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelGreaterThan(Integer value) {
            addCriterion("CUST_LEVEL >", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUST_LEVEL >=", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelLessThan(Integer value) {
            addCriterion("CUST_LEVEL <", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelLessThanOrEqualTo(Integer value) {
            addCriterion("CUST_LEVEL <=", value, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelIn(List<Integer> values) {
            addCriterion("CUST_LEVEL in", values, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelNotIn(List<Integer> values) {
            addCriterion("CUST_LEVEL not in", values, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelBetween(Integer value1, Integer value2) {
            addCriterion("CUST_LEVEL between", value1, value2, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("CUST_LEVEL not between", value1, value2, "custLevel");
            return (Criteria) this;
        }

        public Criteria andCustSexIsNull() {
            addCriterion("CUST_SEX is null");
            return (Criteria) this;
        }

        public Criteria andCustSexIsNotNull() {
            addCriterion("CUST_SEX is not null");
            return (Criteria) this;
        }

        public Criteria andCustSexEqualTo(String value) {
            addCriterion("CUST_SEX =", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexNotEqualTo(String value) {
            addCriterion("CUST_SEX <>", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexGreaterThan(String value) {
            addCriterion("CUST_SEX >", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_SEX >=", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexLessThan(String value) {
            addCriterion("CUST_SEX <", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexLessThanOrEqualTo(String value) {
            addCriterion("CUST_SEX <=", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexLike(String value) {
            addCriterion("CUST_SEX like", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexNotLike(String value) {
            addCriterion("CUST_SEX not like", value, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexIn(List<String> values) {
            addCriterion("CUST_SEX in", values, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexNotIn(List<String> values) {
            addCriterion("CUST_SEX not in", values, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexBetween(String value1, String value2) {
            addCriterion("CUST_SEX between", value1, value2, "custSex");
            return (Criteria) this;
        }

        public Criteria andCustSexNotBetween(String value1, String value2) {
            addCriterion("CUST_SEX not between", value1, value2, "custSex");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateIsNull() {
            addCriterion("WITHDRAW_DATE is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateIsNotNull() {
            addCriterion("WITHDRAW_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateEqualTo(String value) {
            addCriterion("WITHDRAW_DATE =", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateNotEqualTo(String value) {
            addCriterion("WITHDRAW_DATE <>", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateGreaterThan(String value) {
            addCriterion("WITHDRAW_DATE >", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateGreaterThanOrEqualTo(String value) {
            addCriterion("WITHDRAW_DATE >=", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateLessThan(String value) {
            addCriterion("WITHDRAW_DATE <", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateLessThanOrEqualTo(String value) {
            addCriterion("WITHDRAW_DATE <=", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateLike(String value) {
            addCriterion("WITHDRAW_DATE like", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateNotLike(String value) {
            addCriterion("WITHDRAW_DATE not like", value, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateIn(List<String> values) {
            addCriterion("WITHDRAW_DATE in", values, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateNotIn(List<String> values) {
            addCriterion("WITHDRAW_DATE not in", values, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateBetween(String value1, String value2) {
            addCriterion("WITHDRAW_DATE between", value1, value2, "withdrawDate");
            return (Criteria) this;
        }

        public Criteria andWithdrawDateNotBetween(String value1, String value2) {
            addCriterion("WITHDRAW_DATE not between", value1, value2, "withdrawDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_mst
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 06 23:58:54 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_mst
     *
     * @mbggenerated Sun Oct 06 23:58:54 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}