package com.bluezone.bil.domain.cust;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CstCustRecordMstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public CstCustRecordMstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustNoIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCustNoIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCustNoEqualTo(Integer value) {
            addCriterion("CUST_NO =", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotEqualTo(Integer value) {
            addCriterion("CUST_NO <>", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThan(Integer value) {
            addCriterion("CUST_NO >", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUST_NO >=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThan(Integer value) {
            addCriterion("CUST_NO <", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoLessThanOrEqualTo(Integer value) {
            addCriterion("CUST_NO <=", value, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoIn(List<Integer> values) {
            addCriterion("CUST_NO in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotIn(List<Integer> values) {
            addCriterion("CUST_NO not in", values, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoBetween(Integer value1, Integer value2) {
            addCriterion("CUST_NO between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andCustNoNotBetween(Integer value1, Integer value2) {
            addCriterion("CUST_NO not between", value1, value2, "custNo");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNull() {
            addCriterion("REGR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNotNull() {
            addCriterion("REGR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegrIdEqualTo(String value) {
            addCriterion("REGR_ID =", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotEqualTo(String value) {
            addCriterion("REGR_ID <>", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThan(String value) {
            addCriterion("REGR_ID >", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGR_ID >=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThan(String value) {
            addCriterion("REGR_ID <", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThanOrEqualTo(String value) {
            addCriterion("REGR_ID <=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLike(String value) {
            addCriterion("REGR_ID like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotLike(String value) {
            addCriterion("REGR_ID not like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdIn(List<String> values) {
            addCriterion("REGR_ID in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotIn(List<String> values) {
            addCriterion("REGR_ID not in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdBetween(String value1, String value2) {
            addCriterion("REGR_ID between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotBetween(String value1, String value2) {
            addCriterion("REGR_ID not between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNull() {
            addCriterion("UPD_DTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNotNull() {
            addCriterion("UPD_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmEqualTo(Date value) {
            addCriterion("UPD_DTM =", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotEqualTo(Date value) {
            addCriterion("UPD_DTM <>", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThan(Date value) {
            addCriterion("UPD_DTM >", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM >=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThan(Date value) {
            addCriterion("UPD_DTM <", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM <=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIn(List<Date> values) {
            addCriterion("UPD_DTM in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotIn(List<Date> values) {
            addCriterion("UPD_DTM not in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM not between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNull() {
            addCriterion("UPDR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNotNull() {
            addCriterion("UPDR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdEqualTo(String value) {
            addCriterion("UPDR_ID =", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotEqualTo(String value) {
            addCriterion("UPDR_ID <>", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThan(String value) {
            addCriterion("UPDR_ID >", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDR_ID >=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThan(String value) {
            addCriterion("UPDR_ID <", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThanOrEqualTo(String value) {
            addCriterion("UPDR_ID <=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLike(String value) {
            addCriterion("UPDR_ID like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotLike(String value) {
            addCriterion("UPDR_ID not like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIn(List<String> values) {
            addCriterion("UPDR_ID in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotIn(List<String> values) {
            addCriterion("UPDR_ID not in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdBetween(String value1, String value2) {
            addCriterion("UPDR_ID between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotBetween(String value1, String value2) {
            addCriterion("UPDR_ID not between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("SCORE is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("SCORE =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("SCORE <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("SCORE >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("SCORE >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("SCORE <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("SCORE <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("SCORE in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("SCORE not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("SCORE between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("SCORE not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreAvgIsNull() {
            addCriterion("SCORE_AVG is null");
            return (Criteria) this;
        }

        public Criteria andScoreAvgIsNotNull() {
            addCriterion("SCORE_AVG is not null");
            return (Criteria) this;
        }

        public Criteria andScoreAvgEqualTo(Float value) {
            addCriterion("SCORE_AVG =", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgNotEqualTo(Float value) {
            addCriterion("SCORE_AVG <>", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgGreaterThan(Float value) {
            addCriterion("SCORE_AVG >", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgGreaterThanOrEqualTo(Float value) {
            addCriterion("SCORE_AVG >=", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgLessThan(Float value) {
            addCriterion("SCORE_AVG <", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgLessThanOrEqualTo(Float value) {
            addCriterion("SCORE_AVG <=", value, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgIn(List<Float> values) {
            addCriterion("SCORE_AVG in", values, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgNotIn(List<Float> values) {
            addCriterion("SCORE_AVG not in", values, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgBetween(Float value1, Float value2) {
            addCriterion("SCORE_AVG between", value1, value2, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andScoreAvgNotBetween(Float value1, Float value2) {
            addCriterion("SCORE_AVG not between", value1, value2, "scoreAvg");
            return (Criteria) this;
        }

        public Criteria andAvgIsNull() {
            addCriterion("AVG is null");
            return (Criteria) this;
        }

        public Criteria andAvgIsNotNull() {
            addCriterion("AVG is not null");
            return (Criteria) this;
        }

        public Criteria andAvgEqualTo(Float value) {
            addCriterion("AVG =", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotEqualTo(Float value) {
            addCriterion("AVG <>", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThan(Float value) {
            addCriterion("AVG >", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThanOrEqualTo(Float value) {
            addCriterion("AVG >=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThan(Float value) {
            addCriterion("AVG <", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThanOrEqualTo(Float value) {
            addCriterion("AVG <=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgIn(List<Float> values) {
            addCriterion("AVG in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotIn(List<Float> values) {
            addCriterion("AVG not in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgBetween(Float value1, Float value2) {
            addCriterion("AVG between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotBetween(Float value1, Float value2) {
            addCriterion("AVG not between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andHighRunIsNull() {
            addCriterion("HIGH_RUN is null");
            return (Criteria) this;
        }

        public Criteria andHighRunIsNotNull() {
            addCriterion("HIGH_RUN is not null");
            return (Criteria) this;
        }

        public Criteria andHighRunEqualTo(Integer value) {
            addCriterion("HIGH_RUN =", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunNotEqualTo(Integer value) {
            addCriterion("HIGH_RUN <>", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunGreaterThan(Integer value) {
            addCriterion("HIGH_RUN >", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunGreaterThanOrEqualTo(Integer value) {
            addCriterion("HIGH_RUN >=", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunLessThan(Integer value) {
            addCriterion("HIGH_RUN <", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunLessThanOrEqualTo(Integer value) {
            addCriterion("HIGH_RUN <=", value, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunIn(List<Integer> values) {
            addCriterion("HIGH_RUN in", values, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunNotIn(List<Integer> values) {
            addCriterion("HIGH_RUN not in", values, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunBetween(Integer value1, Integer value2) {
            addCriterion("HIGH_RUN between", value1, value2, "highRun");
            return (Criteria) this;
        }

        public Criteria andHighRunNotBetween(Integer value1, Integer value2) {
            addCriterion("HIGH_RUN not between", value1, value2, "highRun");
            return (Criteria) this;
        }

        public Criteria andWinCntIsNull() {
            addCriterion("WIN_CNT is null");
            return (Criteria) this;
        }

        public Criteria andWinCntIsNotNull() {
            addCriterion("WIN_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andWinCntEqualTo(Integer value) {
            addCriterion("WIN_CNT =", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntNotEqualTo(Integer value) {
            addCriterion("WIN_CNT <>", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntGreaterThan(Integer value) {
            addCriterion("WIN_CNT >", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("WIN_CNT >=", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntLessThan(Integer value) {
            addCriterion("WIN_CNT <", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntLessThanOrEqualTo(Integer value) {
            addCriterion("WIN_CNT <=", value, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntIn(List<Integer> values) {
            addCriterion("WIN_CNT in", values, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntNotIn(List<Integer> values) {
            addCriterion("WIN_CNT not in", values, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntBetween(Integer value1, Integer value2) {
            addCriterion("WIN_CNT between", value1, value2, "winCnt");
            return (Criteria) this;
        }

        public Criteria andWinCntNotBetween(Integer value1, Integer value2) {
            addCriterion("WIN_CNT not between", value1, value2, "winCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntIsNull() {
            addCriterion("LOSE_CNT is null");
            return (Criteria) this;
        }

        public Criteria andLoseCntIsNotNull() {
            addCriterion("LOSE_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andLoseCntEqualTo(Integer value) {
            addCriterion("LOSE_CNT =", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntNotEqualTo(Integer value) {
            addCriterion("LOSE_CNT <>", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntGreaterThan(Integer value) {
            addCriterion("LOSE_CNT >", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOSE_CNT >=", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntLessThan(Integer value) {
            addCriterion("LOSE_CNT <", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntLessThanOrEqualTo(Integer value) {
            addCriterion("LOSE_CNT <=", value, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntIn(List<Integer> values) {
            addCriterion("LOSE_CNT in", values, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntNotIn(List<Integer> values) {
            addCriterion("LOSE_CNT not in", values, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntBetween(Integer value1, Integer value2) {
            addCriterion("LOSE_CNT between", value1, value2, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andLoseCntNotBetween(Integer value1, Integer value2) {
            addCriterion("LOSE_CNT not between", value1, value2, "loseCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntIsNull() {
            addCriterion("DRAW_CNT is null");
            return (Criteria) this;
        }

        public Criteria andDrawCntIsNotNull() {
            addCriterion("DRAW_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andDrawCntEqualTo(Integer value) {
            addCriterion("DRAW_CNT =", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntNotEqualTo(Integer value) {
            addCriterion("DRAW_CNT <>", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntGreaterThan(Integer value) {
            addCriterion("DRAW_CNT >", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("DRAW_CNT >=", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntLessThan(Integer value) {
            addCriterion("DRAW_CNT <", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntLessThanOrEqualTo(Integer value) {
            addCriterion("DRAW_CNT <=", value, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntIn(List<Integer> values) {
            addCriterion("DRAW_CNT in", values, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntNotIn(List<Integer> values) {
            addCriterion("DRAW_CNT not in", values, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntBetween(Integer value1, Integer value2) {
            addCriterion("DRAW_CNT between", value1, value2, "drawCnt");
            return (Criteria) this;
        }

        public Criteria andDrawCntNotBetween(Integer value1, Integer value2) {
            addCriterion("DRAW_CNT not between", value1, value2, "drawCnt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 22 21:27:10 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cst_cust_record_mst
     *
     * @mbggenerated Sun Sep 22 21:27:10 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}