package com.bluezone.bil.domain.game;

import java.text.SimpleDateFormat;
import java.util.Date;

public class GameRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer gameRecNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.REG_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.REGR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Date updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.GAME_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer gameNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.CUST_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.INNING
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer inning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer earnScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.AVG
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Float avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.HIGH_RUN
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer highRun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.WIN_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer winCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.LOSE_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer loseCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record.DRAW_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    private Integer drawCnt;
    
    private String strRegDtm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.GAME_REC_NO
     *
     * @return the value of game_record.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getGameRecNo() {
        return gameRecNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.GAME_REC_NO
     *
     * @param gameRecNo the value for game_record.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setGameRecNo(Integer gameRecNo) {
        this.gameRecNo = gameRecNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.REG_DTM
     *
     * @return the value of game_record.REG_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.REG_DTM
     *
     * @param regDtm the value for game_record.REG_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
        this.strRegDtm = format.format(regDtm);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.REGR_ID
     *
     * @return the value of game_record.REGR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.REGR_ID
     *
     * @param regrId the value for game_record.REGR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.UPD_DTM
     *
     * @return the value of game_record.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.UPD_DTM
     *
     * @param updDtm the value for game_record.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setUpdDtm(Date updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.UPDR_ID
     *
     * @return the value of game_record.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.UPDR_ID
     *
     * @param updrId the value for game_record.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.GAME_NO
     *
     * @return the value of game_record.GAME_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getGameNo() {
        return gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.GAME_NO
     *
     * @param gameNo the value for game_record.GAME_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setGameNo(Integer gameNo) {
        this.gameNo = gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.CUST_NO
     *
     * @return the value of game_record.CUST_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.CUST_NO
     *
     * @param custNo the value for game_record.CUST_NO
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setCustNo(Integer custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.SCORE
     *
     * @return the value of game_record.SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.SCORE
     *
     * @param score the value for game_record.SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.INNING
     *
     * @return the value of game_record.INNING
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getInning() {
        return inning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.INNING
     *
     * @param inning the value for game_record.INNING
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setInning(Integer inning) {
        this.inning = inning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.EARN_SCORE
     *
     * @return the value of game_record.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getEarnScore() {
        return earnScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.EARN_SCORE
     *
     * @param earnScore the value for game_record.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setEarnScore(Integer earnScore) {
        this.earnScore = earnScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.AVG
     *
     * @return the value of game_record.AVG
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Float getAvg() {
        return avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.AVG
     *
     * @param avg the value for game_record.AVG
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setAvg(Float avg) {
        this.avg = avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.HIGH_RUN
     *
     * @return the value of game_record.HIGH_RUN
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getHighRun() {
        return highRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.HIGH_RUN
     *
     * @param highRun the value for game_record.HIGH_RUN
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setHighRun(Integer highRun) {
        this.highRun = highRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.WIN_CNT
     *
     * @return the value of game_record.WIN_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getWinCnt() {
        return winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.WIN_CNT
     *
     * @param winCnt the value for game_record.WIN_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setWinCnt(Integer winCnt) {
        this.winCnt = winCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.LOSE_CNT
     *
     * @return the value of game_record.LOSE_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getLoseCnt() {
        return loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.LOSE_CNT
     *
     * @param loseCnt the value for game_record.LOSE_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setLoseCnt(Integer loseCnt) {
        this.loseCnt = loseCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record.DRAW_CNT
     *
     * @return the value of game_record.DRAW_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public Integer getDrawCnt() {
        return drawCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record.DRAW_CNT
     *
     * @param drawCnt the value for game_record.DRAW_CNT
     *
     * @mbggenerated Sun Sep 29 18:04:09 KST 2013
     */
    public void setDrawCnt(Integer drawCnt) {
        this.drawCnt = drawCnt;
    }

	public String getStrRegDtm() {
		return strRegDtm;
	}

	public void setStrRegDtm(String strRegDtm) {
		this.strRegDtm = strRegDtm;
	}
    
}