package com.bluezone.bil.domain.game;

import java.util.Date;

public class GameMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.GAME_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Integer gameNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Date updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.MATCH_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Integer matchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.GAME_NM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private String gameNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.USE_YN
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.GAME_DT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private String gameDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.MEM_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Integer memCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_mst.INNING_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    private Integer inningCnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.GAME_NO
     *
     * @return the value of game_mst.GAME_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Integer getGameNo() {
        return gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.GAME_NO
     *
     * @param gameNo the value for game_mst.GAME_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setGameNo(Integer gameNo) {
        this.gameNo = gameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.REG_DTM
     *
     * @return the value of game_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.REG_DTM
     *
     * @param regDtm the value for game_mst.REG_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.REGR_ID
     *
     * @return the value of game_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.REGR_ID
     *
     * @param regrId the value for game_mst.REGR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.UPD_DTM
     *
     * @return the value of game_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.UPD_DTM
     *
     * @param updDtm the value for game_mst.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setUpdDtm(Date updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.UPDR_ID
     *
     * @return the value of game_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.UPDR_ID
     *
     * @param updrId the value for game_mst.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.MATCH_NO
     *
     * @return the value of game_mst.MATCH_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Integer getMatchNo() {
        return matchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.MATCH_NO
     *
     * @param matchNo the value for game_mst.MATCH_NO
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setMatchNo(Integer matchNo) {
        this.matchNo = matchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.GAME_NM
     *
     * @return the value of game_mst.GAME_NM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public String getGameNm() {
        return gameNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.GAME_NM
     *
     * @param gameNm the value for game_mst.GAME_NM
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setGameNm(String gameNm) {
        this.gameNm = gameNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.USE_YN
     *
     * @return the value of game_mst.USE_YN
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.USE_YN
     *
     * @param useYn the value for game_mst.USE_YN
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.GAME_DT
     *
     * @return the value of game_mst.GAME_DT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public String getGameDt() {
        return gameDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.GAME_DT
     *
     * @param gameDt the value for game_mst.GAME_DT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setGameDt(String gameDt) {
        this.gameDt = gameDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.MEM_CNT
     *
     * @return the value of game_mst.MEM_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Integer getMemCnt() {
        return memCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.MEM_CNT
     *
     * @param memCnt the value for game_mst.MEM_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setMemCnt(Integer memCnt) {
        this.memCnt = memCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_mst.INNING_CNT
     *
     * @return the value of game_mst.INNING_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public Integer getInningCnt() {
        return inningCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_mst.INNING_CNT
     *
     * @param inningCnt the value for game_mst.INNING_CNT
     *
     * @mbggenerated Sun Sep 29 17:03:42 KST 2013
     */
    public void setInningCnt(Integer inningCnt) {
        this.inningCnt = inningCnt;
    }
}