package com.bluezone.bil.domain.game;

import java.util.Date;

public class GameRecordInning {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private Integer gameRecNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.REG_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.REGR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private Date updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.INNING_NUM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private Integer inningNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_record_inning.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    private Integer earnScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.GAME_REC_NO
     *
     * @return the value of game_record_inning.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Integer getGameRecNo() {
        return gameRecNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.GAME_REC_NO
     *
     * @param gameRecNo the value for game_record_inning.GAME_REC_NO
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setGameRecNo(Integer gameRecNo) {
        this.gameRecNo = gameRecNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.REG_DTM
     *
     * @return the value of game_record_inning.REG_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.REG_DTM
     *
     * @param regDtm the value for game_record_inning.REG_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.REGR_ID
     *
     * @return the value of game_record_inning.REGR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.REGR_ID
     *
     * @param regrId the value for game_record_inning.REGR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.UPD_DTM
     *
     * @return the value of game_record_inning.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.UPD_DTM
     *
     * @param updDtm the value for game_record_inning.UPD_DTM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setUpdDtm(Date updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.UPDR_ID
     *
     * @return the value of game_record_inning.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.UPDR_ID
     *
     * @param updrId the value for game_record_inning.UPDR_ID
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.INNING_NUM
     *
     * @return the value of game_record_inning.INNING_NUM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Integer getInningNum() {
        return inningNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.INNING_NUM
     *
     * @param inningNum the value for game_record_inning.INNING_NUM
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setInningNum(Integer inningNum) {
        this.inningNum = inningNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_record_inning.EARN_SCORE
     *
     * @return the value of game_record_inning.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Integer getEarnScore() {
        return earnScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_record_inning.EARN_SCORE
     *
     * @param earnScore the value for game_record_inning.EARN_SCORE
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setEarnScore(Integer earnScore) {
        this.earnScore = earnScore;
    }
}