package com.bluezone.bil.domain.game;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameMstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public GameMstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGameNoIsNull() {
            addCriterion("GAME_NO is null");
            return (Criteria) this;
        }

        public Criteria andGameNoIsNotNull() {
            addCriterion("GAME_NO is not null");
            return (Criteria) this;
        }

        public Criteria andGameNoEqualTo(Integer value) {
            addCriterion("GAME_NO =", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoNotEqualTo(Integer value) {
            addCriterion("GAME_NO <>", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoGreaterThan(Integer value) {
            addCriterion("GAME_NO >", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("GAME_NO >=", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoLessThan(Integer value) {
            addCriterion("GAME_NO <", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoLessThanOrEqualTo(Integer value) {
            addCriterion("GAME_NO <=", value, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoIn(List<Integer> values) {
            addCriterion("GAME_NO in", values, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoNotIn(List<Integer> values) {
            addCriterion("GAME_NO not in", values, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoBetween(Integer value1, Integer value2) {
            addCriterion("GAME_NO between", value1, value2, "gameNo");
            return (Criteria) this;
        }

        public Criteria andGameNoNotBetween(Integer value1, Integer value2) {
            addCriterion("GAME_NO not between", value1, value2, "gameNo");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNull() {
            addCriterion("REGR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNotNull() {
            addCriterion("REGR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegrIdEqualTo(String value) {
            addCriterion("REGR_ID =", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotEqualTo(String value) {
            addCriterion("REGR_ID <>", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThan(String value) {
            addCriterion("REGR_ID >", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGR_ID >=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThan(String value) {
            addCriterion("REGR_ID <", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThanOrEqualTo(String value) {
            addCriterion("REGR_ID <=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLike(String value) {
            addCriterion("REGR_ID like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotLike(String value) {
            addCriterion("REGR_ID not like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdIn(List<String> values) {
            addCriterion("REGR_ID in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotIn(List<String> values) {
            addCriterion("REGR_ID not in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdBetween(String value1, String value2) {
            addCriterion("REGR_ID between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotBetween(String value1, String value2) {
            addCriterion("REGR_ID not between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNull() {
            addCriterion("UPD_DTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNotNull() {
            addCriterion("UPD_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmEqualTo(Date value) {
            addCriterion("UPD_DTM =", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotEqualTo(Date value) {
            addCriterion("UPD_DTM <>", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThan(Date value) {
            addCriterion("UPD_DTM >", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM >=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThan(Date value) {
            addCriterion("UPD_DTM <", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM <=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIn(List<Date> values) {
            addCriterion("UPD_DTM in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotIn(List<Date> values) {
            addCriterion("UPD_DTM not in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM not between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNull() {
            addCriterion("UPDR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNotNull() {
            addCriterion("UPDR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdEqualTo(String value) {
            addCriterion("UPDR_ID =", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotEqualTo(String value) {
            addCriterion("UPDR_ID <>", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThan(String value) {
            addCriterion("UPDR_ID >", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDR_ID >=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThan(String value) {
            addCriterion("UPDR_ID <", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThanOrEqualTo(String value) {
            addCriterion("UPDR_ID <=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLike(String value) {
            addCriterion("UPDR_ID like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotLike(String value) {
            addCriterion("UPDR_ID not like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIn(List<String> values) {
            addCriterion("UPDR_ID in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotIn(List<String> values) {
            addCriterion("UPDR_ID not in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdBetween(String value1, String value2) {
            addCriterion("UPDR_ID between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotBetween(String value1, String value2) {
            addCriterion("UPDR_ID not between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andMatchNoIsNull() {
            addCriterion("MATCH_NO is null");
            return (Criteria) this;
        }

        public Criteria andMatchNoIsNotNull() {
            addCriterion("MATCH_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMatchNoEqualTo(Integer value) {
            addCriterion("MATCH_NO =", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotEqualTo(Integer value) {
            addCriterion("MATCH_NO <>", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThan(Integer value) {
            addCriterion("MATCH_NO >", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_NO >=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThan(Integer value) {
            addCriterion("MATCH_NO <", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_NO <=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoIn(List<Integer> values) {
            addCriterion("MATCH_NO in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotIn(List<Integer> values) {
            addCriterion("MATCH_NO not in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_NO between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_NO not between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andGameNmIsNull() {
            addCriterion("GAME_NM is null");
            return (Criteria) this;
        }

        public Criteria andGameNmIsNotNull() {
            addCriterion("GAME_NM is not null");
            return (Criteria) this;
        }

        public Criteria andGameNmEqualTo(String value) {
            addCriterion("GAME_NM =", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmNotEqualTo(String value) {
            addCriterion("GAME_NM <>", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmGreaterThan(String value) {
            addCriterion("GAME_NM >", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmGreaterThanOrEqualTo(String value) {
            addCriterion("GAME_NM >=", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmLessThan(String value) {
            addCriterion("GAME_NM <", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmLessThanOrEqualTo(String value) {
            addCriterion("GAME_NM <=", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmLike(String value) {
            addCriterion("GAME_NM like", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmNotLike(String value) {
            addCriterion("GAME_NM not like", value, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmIn(List<String> values) {
            addCriterion("GAME_NM in", values, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmNotIn(List<String> values) {
            addCriterion("GAME_NM not in", values, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmBetween(String value1, String value2) {
            addCriterion("GAME_NM between", value1, value2, "gameNm");
            return (Criteria) this;
        }

        public Criteria andGameNmNotBetween(String value1, String value2) {
            addCriterion("GAME_NM not between", value1, value2, "gameNm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGameDtIsNull() {
            addCriterion("GAME_DT is null");
            return (Criteria) this;
        }

        public Criteria andGameDtIsNotNull() {
            addCriterion("GAME_DT is not null");
            return (Criteria) this;
        }

        public Criteria andGameDtEqualTo(String value) {
            addCriterion("GAME_DT =", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtNotEqualTo(String value) {
            addCriterion("GAME_DT <>", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtGreaterThan(String value) {
            addCriterion("GAME_DT >", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtGreaterThanOrEqualTo(String value) {
            addCriterion("GAME_DT >=", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtLessThan(String value) {
            addCriterion("GAME_DT <", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtLessThanOrEqualTo(String value) {
            addCriterion("GAME_DT <=", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtLike(String value) {
            addCriterion("GAME_DT like", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtNotLike(String value) {
            addCriterion("GAME_DT not like", value, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtIn(List<String> values) {
            addCriterion("GAME_DT in", values, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtNotIn(List<String> values) {
            addCriterion("GAME_DT not in", values, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtBetween(String value1, String value2) {
            addCriterion("GAME_DT between", value1, value2, "gameDt");
            return (Criteria) this;
        }

        public Criteria andGameDtNotBetween(String value1, String value2) {
            addCriterion("GAME_DT not between", value1, value2, "gameDt");
            return (Criteria) this;
        }

        public Criteria andMemCntIsNull() {
            addCriterion("MEM_CNT is null");
            return (Criteria) this;
        }

        public Criteria andMemCntIsNotNull() {
            addCriterion("MEM_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andMemCntEqualTo(Integer value) {
            addCriterion("MEM_CNT =", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntNotEqualTo(Integer value) {
            addCriterion("MEM_CNT <>", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntGreaterThan(Integer value) {
            addCriterion("MEM_CNT >", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("MEM_CNT >=", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntLessThan(Integer value) {
            addCriterion("MEM_CNT <", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntLessThanOrEqualTo(Integer value) {
            addCriterion("MEM_CNT <=", value, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntIn(List<Integer> values) {
            addCriterion("MEM_CNT in", values, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntNotIn(List<Integer> values) {
            addCriterion("MEM_CNT not in", values, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntBetween(Integer value1, Integer value2) {
            addCriterion("MEM_CNT between", value1, value2, "memCnt");
            return (Criteria) this;
        }

        public Criteria andMemCntNotBetween(Integer value1, Integer value2) {
            addCriterion("MEM_CNT not between", value1, value2, "memCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntIsNull() {
            addCriterion("INNING_CNT is null");
            return (Criteria) this;
        }

        public Criteria andInningCntIsNotNull() {
            addCriterion("INNING_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andInningCntEqualTo(Integer value) {
            addCriterion("INNING_CNT =", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntNotEqualTo(Integer value) {
            addCriterion("INNING_CNT <>", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntGreaterThan(Integer value) {
            addCriterion("INNING_CNT >", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("INNING_CNT >=", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntLessThan(Integer value) {
            addCriterion("INNING_CNT <", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntLessThanOrEqualTo(Integer value) {
            addCriterion("INNING_CNT <=", value, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntIn(List<Integer> values) {
            addCriterion("INNING_CNT in", values, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntNotIn(List<Integer> values) {
            addCriterion("INNING_CNT not in", values, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntBetween(Integer value1, Integer value2) {
            addCriterion("INNING_CNT between", value1, value2, "inningCnt");
            return (Criteria) this;
        }

        public Criteria andInningCntNotBetween(Integer value1, Integer value2) {
            addCriterion("INNING_CNT not between", value1, value2, "inningCnt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mst
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 03 16:40:45 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_mst
     *
     * @mbggenerated Thu Oct 03 16:40:45 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}