package com.bluezone.bil.domain.game;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameRecordInningExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public GameRecordInningExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGameRecNoIsNull() {
            addCriterion("GAME_REC_NO is null");
            return (Criteria) this;
        }

        public Criteria andGameRecNoIsNotNull() {
            addCriterion("GAME_REC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andGameRecNoEqualTo(Integer value) {
            addCriterion("GAME_REC_NO =", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoNotEqualTo(Integer value) {
            addCriterion("GAME_REC_NO <>", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoGreaterThan(Integer value) {
            addCriterion("GAME_REC_NO >", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("GAME_REC_NO >=", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoLessThan(Integer value) {
            addCriterion("GAME_REC_NO <", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoLessThanOrEqualTo(Integer value) {
            addCriterion("GAME_REC_NO <=", value, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoIn(List<Integer> values) {
            addCriterion("GAME_REC_NO in", values, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoNotIn(List<Integer> values) {
            addCriterion("GAME_REC_NO not in", values, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoBetween(Integer value1, Integer value2) {
            addCriterion("GAME_REC_NO between", value1, value2, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andGameRecNoNotBetween(Integer value1, Integer value2) {
            addCriterion("GAME_REC_NO not between", value1, value2, "gameRecNo");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNull() {
            addCriterion("REGR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNotNull() {
            addCriterion("REGR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegrIdEqualTo(String value) {
            addCriterion("REGR_ID =", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotEqualTo(String value) {
            addCriterion("REGR_ID <>", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThan(String value) {
            addCriterion("REGR_ID >", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGR_ID >=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThan(String value) {
            addCriterion("REGR_ID <", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThanOrEqualTo(String value) {
            addCriterion("REGR_ID <=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLike(String value) {
            addCriterion("REGR_ID like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotLike(String value) {
            addCriterion("REGR_ID not like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdIn(List<String> values) {
            addCriterion("REGR_ID in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotIn(List<String> values) {
            addCriterion("REGR_ID not in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdBetween(String value1, String value2) {
            addCriterion("REGR_ID between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotBetween(String value1, String value2) {
            addCriterion("REGR_ID not between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNull() {
            addCriterion("UPD_DTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNotNull() {
            addCriterion("UPD_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmEqualTo(Date value) {
            addCriterion("UPD_DTM =", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotEqualTo(Date value) {
            addCriterion("UPD_DTM <>", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThan(Date value) {
            addCriterion("UPD_DTM >", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM >=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThan(Date value) {
            addCriterion("UPD_DTM <", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM <=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIn(List<Date> values) {
            addCriterion("UPD_DTM in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotIn(List<Date> values) {
            addCriterion("UPD_DTM not in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM not between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNull() {
            addCriterion("UPDR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNotNull() {
            addCriterion("UPDR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdEqualTo(String value) {
            addCriterion("UPDR_ID =", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotEqualTo(String value) {
            addCriterion("UPDR_ID <>", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThan(String value) {
            addCriterion("UPDR_ID >", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDR_ID >=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThan(String value) {
            addCriterion("UPDR_ID <", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThanOrEqualTo(String value) {
            addCriterion("UPDR_ID <=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLike(String value) {
            addCriterion("UPDR_ID like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotLike(String value) {
            addCriterion("UPDR_ID not like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIn(List<String> values) {
            addCriterion("UPDR_ID in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotIn(List<String> values) {
            addCriterion("UPDR_ID not in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdBetween(String value1, String value2) {
            addCriterion("UPDR_ID between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotBetween(String value1, String value2) {
            addCriterion("UPDR_ID not between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andInningNumIsNull() {
            addCriterion("INNING_NUM is null");
            return (Criteria) this;
        }

        public Criteria andInningNumIsNotNull() {
            addCriterion("INNING_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andInningNumEqualTo(Integer value) {
            addCriterion("INNING_NUM =", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumNotEqualTo(Integer value) {
            addCriterion("INNING_NUM <>", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumGreaterThan(Integer value) {
            addCriterion("INNING_NUM >", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("INNING_NUM >=", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumLessThan(Integer value) {
            addCriterion("INNING_NUM <", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumLessThanOrEqualTo(Integer value) {
            addCriterion("INNING_NUM <=", value, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumIn(List<Integer> values) {
            addCriterion("INNING_NUM in", values, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumNotIn(List<Integer> values) {
            addCriterion("INNING_NUM not in", values, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumBetween(Integer value1, Integer value2) {
            addCriterion("INNING_NUM between", value1, value2, "inningNum");
            return (Criteria) this;
        }

        public Criteria andInningNumNotBetween(Integer value1, Integer value2) {
            addCriterion("INNING_NUM not between", value1, value2, "inningNum");
            return (Criteria) this;
        }

        public Criteria andEarnScoreIsNull() {
            addCriterion("EARN_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andEarnScoreIsNotNull() {
            addCriterion("EARN_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andEarnScoreEqualTo(Integer value) {
            addCriterion("EARN_SCORE =", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreNotEqualTo(Integer value) {
            addCriterion("EARN_SCORE <>", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreGreaterThan(Integer value) {
            addCriterion("EARN_SCORE >", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("EARN_SCORE >=", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreLessThan(Integer value) {
            addCriterion("EARN_SCORE <", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreLessThanOrEqualTo(Integer value) {
            addCriterion("EARN_SCORE <=", value, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreIn(List<Integer> values) {
            addCriterion("EARN_SCORE in", values, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreNotIn(List<Integer> values) {
            addCriterion("EARN_SCORE not in", values, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreBetween(Integer value1, Integer value2) {
            addCriterion("EARN_SCORE between", value1, value2, "earnScore");
            return (Criteria) this;
        }

        public Criteria andEarnScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("EARN_SCORE not between", value1, value2, "earnScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_record_inning
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 29 11:04:12 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_record_inning
     *
     * @mbggenerated Sun Sep 29 11:04:12 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}