package com.bluezone.bil.domain.game;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MatchMstExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public MatchMstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMatchNoIsNull() {
            addCriterion("MATCH_NO is null");
            return (Criteria) this;
        }

        public Criteria andMatchNoIsNotNull() {
            addCriterion("MATCH_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMatchNoEqualTo(Integer value) {
            addCriterion("MATCH_NO =", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotEqualTo(Integer value) {
            addCriterion("MATCH_NO <>", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThan(Integer value) {
            addCriterion("MATCH_NO >", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("MATCH_NO >=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThan(Integer value) {
            addCriterion("MATCH_NO <", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThanOrEqualTo(Integer value) {
            addCriterion("MATCH_NO <=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoIn(List<Integer> values) {
            addCriterion("MATCH_NO in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotIn(List<Integer> values) {
            addCriterion("MATCH_NO not in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_NO between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotBetween(Integer value1, Integer value2) {
            addCriterion("MATCH_NO not between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNull() {
            addCriterion("REG_DTM is null");
            return (Criteria) this;
        }

        public Criteria andRegDtmIsNotNull() {
            addCriterion("REG_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andRegDtmEqualTo(Date value) {
            addCriterion("REG_DTM =", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotEqualTo(Date value) {
            addCriterion("REG_DTM <>", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThan(Date value) {
            addCriterion("REG_DTM >", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DTM >=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThan(Date value) {
            addCriterion("REG_DTM <", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmLessThanOrEqualTo(Date value) {
            addCriterion("REG_DTM <=", value, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmIn(List<Date> values) {
            addCriterion("REG_DTM in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotIn(List<Date> values) {
            addCriterion("REG_DTM not in", values, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmBetween(Date value1, Date value2) {
            addCriterion("REG_DTM between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegDtmNotBetween(Date value1, Date value2) {
            addCriterion("REG_DTM not between", value1, value2, "regDtm");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNull() {
            addCriterion("REGR_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegrIdIsNotNull() {
            addCriterion("REGR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegrIdEqualTo(String value) {
            addCriterion("REGR_ID =", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotEqualTo(String value) {
            addCriterion("REGR_ID <>", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThan(String value) {
            addCriterion("REGR_ID >", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGR_ID >=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThan(String value) {
            addCriterion("REGR_ID <", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLessThanOrEqualTo(String value) {
            addCriterion("REGR_ID <=", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdLike(String value) {
            addCriterion("REGR_ID like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotLike(String value) {
            addCriterion("REGR_ID not like", value, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdIn(List<String> values) {
            addCriterion("REGR_ID in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotIn(List<String> values) {
            addCriterion("REGR_ID not in", values, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdBetween(String value1, String value2) {
            addCriterion("REGR_ID between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andRegrIdNotBetween(String value1, String value2) {
            addCriterion("REGR_ID not between", value1, value2, "regrId");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNull() {
            addCriterion("UPD_DTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIsNotNull() {
            addCriterion("UPD_DTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDtmEqualTo(Date value) {
            addCriterion("UPD_DTM =", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotEqualTo(Date value) {
            addCriterion("UPD_DTM <>", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThan(Date value) {
            addCriterion("UPD_DTM >", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM >=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThan(Date value) {
            addCriterion("UPD_DTM <", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DTM <=", value, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmIn(List<Date> values) {
            addCriterion("UPD_DTM in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotIn(List<Date> values) {
            addCriterion("UPD_DTM not in", values, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdDtmNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DTM not between", value1, value2, "updDtm");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNull() {
            addCriterion("UPDR_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIsNotNull() {
            addCriterion("UPDR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdrIdEqualTo(String value) {
            addCriterion("UPDR_ID =", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotEqualTo(String value) {
            addCriterion("UPDR_ID <>", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThan(String value) {
            addCriterion("UPDR_ID >", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDR_ID >=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThan(String value) {
            addCriterion("UPDR_ID <", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLessThanOrEqualTo(String value) {
            addCriterion("UPDR_ID <=", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdLike(String value) {
            addCriterion("UPDR_ID like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotLike(String value) {
            addCriterion("UPDR_ID not like", value, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdIn(List<String> values) {
            addCriterion("UPDR_ID in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotIn(List<String> values) {
            addCriterion("UPDR_ID not in", values, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdBetween(String value1, String value2) {
            addCriterion("UPDR_ID between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andUpdrIdNotBetween(String value1, String value2) {
            addCriterion("UPDR_ID not between", value1, value2, "updrId");
            return (Criteria) this;
        }

        public Criteria andMatchNmIsNull() {
            addCriterion("MATCH_NM is null");
            return (Criteria) this;
        }

        public Criteria andMatchNmIsNotNull() {
            addCriterion("MATCH_NM is not null");
            return (Criteria) this;
        }

        public Criteria andMatchNmEqualTo(String value) {
            addCriterion("MATCH_NM =", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmNotEqualTo(String value) {
            addCriterion("MATCH_NM <>", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmGreaterThan(String value) {
            addCriterion("MATCH_NM >", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmGreaterThanOrEqualTo(String value) {
            addCriterion("MATCH_NM >=", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmLessThan(String value) {
            addCriterion("MATCH_NM <", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmLessThanOrEqualTo(String value) {
            addCriterion("MATCH_NM <=", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmLike(String value) {
            addCriterion("MATCH_NM like", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmNotLike(String value) {
            addCriterion("MATCH_NM not like", value, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmIn(List<String> values) {
            addCriterion("MATCH_NM in", values, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmNotIn(List<String> values) {
            addCriterion("MATCH_NM not in", values, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmBetween(String value1, String value2) {
            addCriterion("MATCH_NM between", value1, value2, "matchNm");
            return (Criteria) this;
        }

        public Criteria andMatchNmNotBetween(String value1, String value2) {
            addCriterion("MATCH_NM not between", value1, value2, "matchNm");
            return (Criteria) this;
        }

        public Criteria andUseYnIsNull() {
            addCriterion("USE_YN is null");
            return (Criteria) this;
        }

        public Criteria andUseYnIsNotNull() {
            addCriterion("USE_YN is not null");
            return (Criteria) this;
        }

        public Criteria andUseYnEqualTo(String value) {
            addCriterion("USE_YN =", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotEqualTo(String value) {
            addCriterion("USE_YN <>", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnGreaterThan(String value) {
            addCriterion("USE_YN >", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnGreaterThanOrEqualTo(String value) {
            addCriterion("USE_YN >=", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLessThan(String value) {
            addCriterion("USE_YN <", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLessThanOrEqualTo(String value) {
            addCriterion("USE_YN <=", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnLike(String value) {
            addCriterion("USE_YN like", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotLike(String value) {
            addCriterion("USE_YN not like", value, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnIn(List<String> values) {
            addCriterion("USE_YN in", values, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotIn(List<String> values) {
            addCriterion("USE_YN not in", values, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnBetween(String value1, String value2) {
            addCriterion("USE_YN between", value1, value2, "useYn");
            return (Criteria) this;
        }

        public Criteria andUseYnNotBetween(String value1, String value2) {
            addCriterion("USE_YN not between", value1, value2, "useYn");
            return (Criteria) this;
        }

        public Criteria andYyyymmIsNull() {
            addCriterion("YYYYMM is null");
            return (Criteria) this;
        }

        public Criteria andYyyymmIsNotNull() {
            addCriterion("YYYYMM is not null");
            return (Criteria) this;
        }

        public Criteria andYyyymmEqualTo(String value) {
            addCriterion("YYYYMM =", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmNotEqualTo(String value) {
            addCriterion("YYYYMM <>", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmGreaterThan(String value) {
            addCriterion("YYYYMM >", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmGreaterThanOrEqualTo(String value) {
            addCriterion("YYYYMM >=", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmLessThan(String value) {
            addCriterion("YYYYMM <", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmLessThanOrEqualTo(String value) {
            addCriterion("YYYYMM <=", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmLike(String value) {
            addCriterion("YYYYMM like", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmNotLike(String value) {
            addCriterion("YYYYMM not like", value, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmIn(List<String> values) {
            addCriterion("YYYYMM in", values, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmNotIn(List<String> values) {
            addCriterion("YYYYMM not in", values, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmBetween(String value1, String value2) {
            addCriterion("YYYYMM between", value1, value2, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andYyyymmNotBetween(String value1, String value2) {
            addCriterion("YYYYMM not between", value1, value2, "yyyymm");
            return (Criteria) this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("WEEK is null");
            return (Criteria) this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("WEEK is not null");
            return (Criteria) this;
        }

        public Criteria andWeekEqualTo(String value) {
            addCriterion("WEEK =", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotEqualTo(String value) {
            addCriterion("WEEK <>", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThan(String value) {
            addCriterion("WEEK >", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(String value) {
            addCriterion("WEEK >=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThan(String value) {
            addCriterion("WEEK <", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLessThanOrEqualTo(String value) {
            addCriterion("WEEK <=", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekLike(String value) {
            addCriterion("WEEK like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotLike(String value) {
            addCriterion("WEEK not like", value, "week");
            return (Criteria) this;
        }

        public Criteria andWeekIn(List<String> values) {
            addCriterion("WEEK in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotIn(List<String> values) {
            addCriterion("WEEK not in", values, "week");
            return (Criteria) this;
        }

        public Criteria andWeekBetween(String value1, String value2) {
            addCriterion("WEEK between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andWeekNotBetween(String value1, String value2) {
            addCriterion("WEEK not between", value1, value2, "week");
            return (Criteria) this;
        }

        public Criteria andStdDtIsNull() {
            addCriterion("STD_DT is null");
            return (Criteria) this;
        }

        public Criteria andStdDtIsNotNull() {
            addCriterion("STD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andStdDtEqualTo(String value) {
            addCriterion("STD_DT =", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtNotEqualTo(String value) {
            addCriterion("STD_DT <>", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtGreaterThan(String value) {
            addCriterion("STD_DT >", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtGreaterThanOrEqualTo(String value) {
            addCriterion("STD_DT >=", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtLessThan(String value) {
            addCriterion("STD_DT <", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtLessThanOrEqualTo(String value) {
            addCriterion("STD_DT <=", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtLike(String value) {
            addCriterion("STD_DT like", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtNotLike(String value) {
            addCriterion("STD_DT not like", value, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtIn(List<String> values) {
            addCriterion("STD_DT in", values, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtNotIn(List<String> values) {
            addCriterion("STD_DT not in", values, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtBetween(String value1, String value2) {
            addCriterion("STD_DT between", value1, value2, "stdDt");
            return (Criteria) this;
        }

        public Criteria andStdDtNotBetween(String value1, String value2) {
            addCriterion("STD_DT not between", value1, value2, "stdDt");
            return (Criteria) this;
        }

        public Criteria andEndDtIsNull() {
            addCriterion("END_DT is null");
            return (Criteria) this;
        }

        public Criteria andEndDtIsNotNull() {
            addCriterion("END_DT is not null");
            return (Criteria) this;
        }

        public Criteria andEndDtEqualTo(String value) {
            addCriterion("END_DT =", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotEqualTo(String value) {
            addCriterion("END_DT <>", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtGreaterThan(String value) {
            addCriterion("END_DT >", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtGreaterThanOrEqualTo(String value) {
            addCriterion("END_DT >=", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtLessThan(String value) {
            addCriterion("END_DT <", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtLessThanOrEqualTo(String value) {
            addCriterion("END_DT <=", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtLike(String value) {
            addCriterion("END_DT like", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotLike(String value) {
            addCriterion("END_DT not like", value, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtIn(List<String> values) {
            addCriterion("END_DT in", values, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotIn(List<String> values) {
            addCriterion("END_DT not in", values, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtBetween(String value1, String value2) {
            addCriterion("END_DT between", value1, value2, "endDt");
            return (Criteria) this;
        }

        public Criteria andEndDtNotBetween(String value1, String value2) {
            addCriterion("END_DT not between", value1, value2, "endDt");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNull() {
            addCriterion("MATCH_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNotNull() {
            addCriterion("MATCH_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeEqualTo(String value) {
            addCriterion("MATCH_TYPE =", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotEqualTo(String value) {
            addCriterion("MATCH_TYPE <>", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThan(String value) {
            addCriterion("MATCH_TYPE >", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MATCH_TYPE >=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThan(String value) {
            addCriterion("MATCH_TYPE <", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThanOrEqualTo(String value) {
            addCriterion("MATCH_TYPE <=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLike(String value) {
            addCriterion("MATCH_TYPE like", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotLike(String value) {
            addCriterion("MATCH_TYPE not like", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIn(List<String> values) {
            addCriterion("MATCH_TYPE in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotIn(List<String> values) {
            addCriterion("MATCH_TYPE not in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeBetween(String value1, String value2) {
            addCriterion("MATCH_TYPE between", value1, value2, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotBetween(String value1, String value2) {
            addCriterion("MATCH_TYPE not between", value1, value2, "matchType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_mst
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 03 17:27:29 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table match_mst
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}