package com.bluezone.bil.domain.game;

import java.util.Date;

public class MatchMst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.MATCH_NO
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private Integer matchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.REG_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private Date regDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.REGR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String regrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.UPD_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private Date updDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.UPDR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String updrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.MATCH_NM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String matchNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.USE_YN
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.YYYYMM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String yyyymm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.WEEK
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.STD_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String stdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.END_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String endDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_mst.MATCH_TYPE
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    private String matchType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.MATCH_NO
     *
     * @return the value of match_mst.MATCH_NO
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public Integer getMatchNo() {
        return matchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.MATCH_NO
     *
     * @param matchNo the value for match_mst.MATCH_NO
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setMatchNo(Integer matchNo) {
        this.matchNo = matchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.REG_DTM
     *
     * @return the value of match_mst.REG_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public Date getRegDtm() {
        return regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.REG_DTM
     *
     * @param regDtm the value for match_mst.REG_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setRegDtm(Date regDtm) {
        this.regDtm = regDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.REGR_ID
     *
     * @return the value of match_mst.REGR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getRegrId() {
        return regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.REGR_ID
     *
     * @param regrId the value for match_mst.REGR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setRegrId(String regrId) {
        this.regrId = regrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.UPD_DTM
     *
     * @return the value of match_mst.UPD_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public Date getUpdDtm() {
        return updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.UPD_DTM
     *
     * @param updDtm the value for match_mst.UPD_DTM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setUpdDtm(Date updDtm) {
        this.updDtm = updDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.UPDR_ID
     *
     * @return the value of match_mst.UPDR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getUpdrId() {
        return updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.UPDR_ID
     *
     * @param updrId the value for match_mst.UPDR_ID
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setUpdrId(String updrId) {
        this.updrId = updrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.MATCH_NM
     *
     * @return the value of match_mst.MATCH_NM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getMatchNm() {
        return matchNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.MATCH_NM
     *
     * @param matchNm the value for match_mst.MATCH_NM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setMatchNm(String matchNm) {
        this.matchNm = matchNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.USE_YN
     *
     * @return the value of match_mst.USE_YN
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.USE_YN
     *
     * @param useYn the value for match_mst.USE_YN
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.YYYYMM
     *
     * @return the value of match_mst.YYYYMM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getYyyymm() {
        return yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.YYYYMM
     *
     * @param yyyymm the value for match_mst.YYYYMM
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setYyyymm(String yyyymm) {
        this.yyyymm = yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.WEEK
     *
     * @return the value of match_mst.WEEK
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.WEEK
     *
     * @param week the value for match_mst.WEEK
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setWeek(String week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.STD_DT
     *
     * @return the value of match_mst.STD_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getStdDt() {
        return stdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.STD_DT
     *
     * @param stdDt the value for match_mst.STD_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setStdDt(String stdDt) {
        this.stdDt = stdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.END_DT
     *
     * @return the value of match_mst.END_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.END_DT
     *
     * @param endDt the value for match_mst.END_DT
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setEndDt(String endDt) {
        this.endDt = endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_mst.MATCH_TYPE
     *
     * @return the value of match_mst.MATCH_TYPE
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public String getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_mst.MATCH_TYPE
     *
     * @param matchType the value for match_mst.MATCH_TYPE
     *
     * @mbggenerated Thu Oct 03 17:27:29 KST 2013
     */
    public void setMatchType(String matchType) {
        this.matchType = matchType;
    }
}